---
creation_rules:
  - # Encrypt .env files
    path_regex: (apps|containers)/.+\.sops\.env
    input_type: dotenv
    key_groups:
      - age:
          - age1t65e2jjrlhe63w9caspzl4yrughss8l5vph7zvz27jk7ly5jh36q66pkdp
  - # Encrypt .json and bind's .key files
    path_regex: (apps|containers)/.+\.sops\.(json|key)
    input_type: json
    key_groups:
      - age:
          - age1t65e2jjrlhe63w9caspzl4yrughss8l5vph7zvz27jk7ly5jh36q66pkdp
stores:
  yaml:
    indent: 2
